"""Tools package for multi-tenant-github-mcp MCP server.

This file is automatically generated by the dynamic loading system.
Do not edit manually - it will be overwritten when tools are loaded.
"""

from .echo import echo
from .list_private_repos import list_private_repos

__all__ = ["echo", "list_private_repos"]
